### Application version ###
applicationVersion=2.0.1-SNAPSHOT

### Project configs ###
projectGroup=com.hibitbackendimproved
javaVersion=21

### Spring dependency versions ###
springBootVersion=3.3.2
springDependencyManagementVersion=1.1.6

### Plugin versions ###
jacocoVersion=0.8.12
asciidoctorConvertVersion=4.0.2

### Dependency versions ###
mysqlConnectorVersion=8.3.0
restAssuredVersion=5.5.0
jjwtVersion=0.11.5
